/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manufakturmithlabs;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MithLabs
 */
public class HargaJual extends javax.swing.JFrame {
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    private DefaultTableModel tabmode;
    private DefaultTableModel tabmode2;
    private DefaultTableModel tabmode3;

    /**
     * Creates new form HargaJual
     */
    public HargaJual() {
        
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        initComponents();
        datatable();
        datatable3();
        
    }
    
    protected void datatable(){
        Object[] Baris = {"Nama Barang","SKU Barang","Jumlah Barang","HPP"};
        tabmode = new DefaultTableModel(null,Baris);
        TabBarangJadi.setModel(tabmode);
        
        try{
            sql = "SELECT `namabarangjadi`, `SKUBarang`, `jumlahbarang`, `hpp` FROM `proses` WHERE status ='jadi'";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                String a = rs.getString("namabarangjadi");
                String b = rs.getString("SKUbarang");
                String c = rs.getString("jumlahbarang");
                String d = rs.getString("hpp");
                String[] data = {a,b,c,d};
                tabmode.addRow(data);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Gagal Load Data Barang Jadi");
        }
    }
    
    public void datatable2(){
        Object [] Baris2 ={1,2,3,4,5};
        tabmode2 = new DefaultTableModel(null,Baris2);
        
        try{
            sql = "SELECT `namabarangjadi`, `SKUBarang`, `jumlahbarang`, `hpp` FROM `proses` WHERE status = 'jadi'";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                String a = rs.getString("namabarangjadi");
                String b = rs.getString("SKUbarang");
                String c = rs.getString("jumlahbarang");
                String d = rs.getString("hpp");
                String[] data = {a,b,c,d};
                tabmode2.addRow(data);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void datatable3(){
        Object [] Baris3 ={"SKU Barang","Nama Barang","Jumlah Barang","HPP","Margin", "Harga Jual"};
        tabmode3 = new DefaultTableModel(null,Baris3);
        TabHargaJual.setModel(tabmode3);
        
        try{
            sql = "SELECT `skubarang`, `namabarang`, `jumlahbarang`, `hpp`, `margin`, `hargajual` FROM `harga`";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                String a = rs.getString("skubarang");
                String b = rs.getString("namabarang");
                String c = rs.getString("jumlahbarang");
                String d = rs.getString("hpp");
                String e = rs.getString("margin");
                String f = rs.getString("hargajual");
                
                String[] data = {a,b,c,d,e,f};
                tabmode3.addRow(data);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void bersih(){
        tSkuBarang.setText("");
        tNamaBarang.setText("");
        tJumlahBarang.setText("");
        tHPP.setText("");
        tMargin.setText("");
        tHargaJual.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabBarangJadi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tHPP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabHargaJual = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        bCalculate = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        tSkuBarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tNamaBarang = new javax.swing.JTextField();
        tJumlahBarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tHargaJual = new javax.swing.JTextField();
        tMargin = new javax.swing.JTextField();
        bHome = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tSkuBarangHarga = new javax.swing.JTextField();
        bDeleteHargaJual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Harga Jual");

        TabBarangJadi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabBarangJadi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabBarangJadiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabBarangJadi);

        jLabel2.setText("Barang Jadi");

        jLabel3.setText("HPP ");

        jLabel4.setText("Margin");

        jLabel5.setText("%");

        TabHargaJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabHargaJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabHargaJualMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabHargaJual);

        jLabel6.setText("Harga Jual");

        bCalculate.setText("Calculate");
        bCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalculateActionPerformed(evt);
            }
        });

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bUpdate.setText("Update");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bDelete.setText("Delete - Barang Jadi");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        jLabel8.setText("SKU Barang");

        jLabel9.setText("Nama Barang ");

        jLabel10.setText("Jumlah Barang");

        jLabel11.setText("Harga Jual");

        tMargin.setText("0");

        bHome.setText("Home");
        bHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHomeActionPerformed(evt);
            }
        });

        jLabel12.setText("SKU Barang - Harga");

        tSkuBarangHarga.setEditable(false);

        bDeleteHargaJual.setText("Delete - Harga Jual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(tSkuBarangHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bDeleteHargaJual))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(tHargaJual))
                                .addComponent(bCalculate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(tHPP, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tSkuBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bDelete)
                            .addComponent(bHome))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tSkuBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tHPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bUpdate)
                        .addComponent(bHome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tSkuBarangHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDeleteHargaJual))
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabBarangJadiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabBarangJadiMouseClicked
        // TODO add your handling code here:
        datatable2();
        int bar = TabBarangJadi.getSelectedRow();
        String a = tabmode2.getValueAt(bar,0).toString();
        String b = tabmode2.getValueAt(bar,1).toString();
        String c = tabmode2.getValueAt(bar,2).toString();
        String d = tabmode2.getValueAt(bar,3).toString();
        
        tSkuBarang.setText(b);
        tNamaBarang.setText(a);
        tJumlahBarang.setText(c);
        tHPP.setText(d);
    }//GEN-LAST:event_TabBarangJadiMouseClicked

    private void bCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalculateActionPerformed
        // TODO add your handling code here:
        float hargaJual = 0 ;
        float hpp = 0;
        float margin = 0;
        
        hpp = Float.parseFloat(tHPP.getText());
        margin = Float.parseFloat(tMargin.getText());
        hargaJual = (hpp * margin / 100)+hpp;
        tHargaJual.setText(String.valueOf(hargaJual));
    }//GEN-LAST:event_bCalculateActionPerformed

    private void bHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHomeActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_bHomeActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        try{
            sql = "INSERT INTO `harga`(`skubarang`, `namabarang`, `jumlahbarang`, `hpp`, `margin`, `hargajual`) VALUES (?,?,?,?,?,?)";
            java.sql.PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, tSkuBarang.getText());
            stat.setString(2, tNamaBarang.getText());
            stat.setString(3, tJumlahBarang.getText());
            stat.setString(4, tHPP.getText());
            stat.setString(5, tMargin.getText());
            stat.setString(6, tHargaJual.getText());
            stat.executeUpdate();
            tSkuBarang.requestFocus();
            datatable();
            datatable3();
            bersih();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus Barang Jadi? \nStock bahan yang sudah terpakai tidak kembali","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok==0){
            try{
                sql="DELETE FROM `proses` WHERE SKUBarang = '"+tSkuBarang.getText()+"'";
                java.sql.PreparedStatement stat = con.prepareStatement(sql);
                stat.executeUpdate();
                tSkuBarang.requestFocus();
                datatable();
                bersih();
                JOptionPane.showMessageDialog(null,"Data Barang Jadi Berhasil Dihapus");            
            } catch (Exception e){
                JOptionPane.showMessageDialog(null,"Data Barang Jadi Gagal Dihapus"+e);
            }
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        // TODO add your handling code here:
        try{
            sql = "UPDATE `harga` SET `skubarang`=?,`namabarang`=?,`jumlahbarang`=?,`hpp`=?,`margin`=?,`hargajual`=? WHERE skubarang =?";
            java.sql.PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, tSkuBarang.getText());
            stat.setString(2, tNamaBarang.getText());
            stat.setString(3, tJumlahBarang.getText());
            stat.setString(4, tHPP.getText());
            stat.setString(5, tSkuBarang.getText());
            stat.executeUpdate();
            tSkuBarang.requestFocus();
            datatable();
            bersih();
            JOptionPane.showMessageDialog(null,"Data Barang Jadi Berhasil Diubah");            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Barang Jadi Gagal Diubah");
        }
    }//GEN-LAST:event_bUpdateActionPerformed

    private void TabHargaJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabHargaJualMouseClicked
        // TODO add your handling code here:
        datatable3();
        int bar = TabHargaJual.getSelectedRow();
        String a = tabmode2.getValueAt(bar,0).toString();
        
        tSkuBarangHarga.setText(a);
         
    }//GEN-LAST:event_TabHargaJualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HargaJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HargaJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HargaJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HargaJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HargaJual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabBarangJadi;
    private javax.swing.JTable TabHargaJual;
    private javax.swing.JButton bCalculate;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bDeleteHargaJual;
    private javax.swing.JButton bHome;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tHPP;
    private javax.swing.JTextField tHargaJual;
    private javax.swing.JTextField tJumlahBarang;
    private javax.swing.JTextField tMargin;
    private javax.swing.JTextField tNamaBarang;
    private javax.swing.JTextField tSkuBarang;
    private javax.swing.JTextField tSkuBarangHarga;
    // End of variables declaration//GEN-END:variables
}
